log:
  level: error
  format: text
  
  console:
    enabled: false
  
  file:
    enabled: true
    path: "./test-data/logs"
    filename: "lazispace-test.log"
    maxSizeMB: 5
    maxBackups: 1
    maxAgeDays: 1
    compress: false

storage:
  useXDG: false
  configDir: "./test-data/config"
  dataDir: "./test-data/data"
